# Simple Kubernetes Pod to deploy the app contained in chetankamadinni/docker-sample:1.0
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: chetankamadinni/docker-sample:1.0
      ports:
        - containerPort: 8085